### PR TITLE
Update index.gsp

### PR DESCRIPTION
**Pull request by puneetbehl**

### CODE REVIEW

**Comment by lRaulMN7** [comment]
Thanks for taking a look at the issue @puneetbehl . What is this pull request for? 
I suppose it is just a code improvement, right? Because I still have the same issue with those changes >.<
I'll accept the pull anyways.

**Comment by puneetbehl** [comment]
It works fine for me after this change.
Screenshot 2020-03-05 at 4 54 52 PM

**Comment by lRaulMN7** [comment]
image

It doesn't work for me... and I'm using your code. I'm typing 0,69 in the input field. I could do a video if you need it... @puneetbehl

**Comment by lRaulMN7** [comment]
?

**Comment by puneetbehl** [comment]
Shouldn't it be 0.69 instead of a comma.

**Comment by lRaulMN7** [comment]
In Spain, the decimal notation is represented with a comma, but anyways they both fail and return the same log.info message
We're not in a hurry anymore with this issue, but we definitely have problems with this... We can run any project and show you the logs for you to help us, but we're kinda out of ideas to solve it.

**Comment by lRaulMN7** [comment]
@puneetbehl

**Pull request merged**
